### ISSUE TITLE
hello leido

### ISSUE THREAD

**Issue by mrlonely001** [leido/char-rnn-cn#2]
你的gen_lyrics.py 运行会报错  提示tensorflow:<tensorflow.python.ops.rnn_cell_BasicLSTMCell object at ox7f5d028cae10>      我是python 3.5   难道环境有问题？

**Comment by leido** [comment]
@mrlonely001 
我更新了代码，需要升级tensorflow到最新版本：0.12.0rc0，你重新clone试试？

**Comment by mrlonely001** [comment]
好 我试试
